plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

url: https://samanthasays.github.io
title: Samantha Says
tagline: The personal website of Samantha Says
description: The personal website of Samantha Says, featuring her writings, characters, mod lists, screenshots, artwork, and more.
author: SamanthaSaysTV
locale: en_GB
twitter:
  username: SamanthaSaysTV
  card: summary_large_image
social:
  name: Samantha Says
links:
  - https://samanthasays.net
  - https://twitch.tv/SamanthaSays
  - https://twitter.com/SamanthaSaysTV

feed:
  posts_limit: 20
  excerpt_only: true
  disable_in_development: true

paginate: 10
paginate_path: "/posts/:num/"

collections:
  mods:
    output: true
    permalink: mods/:path
  characters:
    output: true
    permalink: characters/:path