plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

url: https://samanthasays.net
title: Samantha Says
tagline: The personal website of Samantha Says
description: The personal website of Samantha Says, featuring her writings, characters, mod lists, screenshots, artwork, and more.
author: SamanthaSaysTV
locale: en_GB
twitter:
  username: SamanthaSaysTV
  card: summary
social:
  name: Samantha Says
links:
  - https://samanthasays.net
  - https://shop.samanthasays.net
  - https://twitch.samanthasays.net

feed:
  posts_limit: 10
  excerpt_only: true
  disable_in_development: true

paginate: 10
paginate_path: "/posts/:num/"

collections:
  mods:
    output: true
    permalink: mods/:path
  charactersESO:
    output: true
    permalink: characters/eso/:path
  charactersMW:
    output: true
    permalink: characters/morrowind/:path