plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

url: https://samanthasays.github.io
title: Samantha Says
tagline: The personal website of Samantha Says
description: The personal website of Samantha Says, featuring her writings, characters, mod lists, screenshots, artwork, and more.
author: SamanthaSaysTV
locale: en_GB
twitter:
  username: SamanthaSaysTV
  card: summary_large_image
google_site_verification: S0qEL3MgZEMkPuMCDk1veH1JPgWzBQiw259Min7CoOQ
social:
  name: Samantha Says
  links:
    - https://samanthasays.github.io
    - https://twitch.tv/SamanthaSays
    - https://twitter.com/SamanthaSaysTV

feed:
  posts_limit: 20
  excerpt_only: true
  tags: true
  disable_in_development: true